export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_DELETE_ITEM = 'CART_DELETE_ITEM';
export const CART_SAVE_SHIPPING_DETAILS = 'CART_SAVE_SHIPPING_DETAILS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const CART_ITEMS_RESET = 'CART_ITEMS_RESET';